### ISSUE TITLE
Failed to verify second signature

### ISSUE THREAD

**Issue by ghost** [fix/Lisk-Lite-Client#10]
Can't send funds while using multi-sig account.

**Comment by fix** [comment]
no, only second signature working, not multisignature.
Note there is a bug in current beta that prevents to take into account the sender address. Maybe this is linked

**Comment by ghost** [comment]
I have tried to send transaction from account with enabled 2nd passphrase. As requested i have filled up both passphrases which resulted with "Failed to verify second signature"

**Comment by fix** [comment]
yes, the transaction is not filled properly with sender address... fixing next release

**Comment by yelllowsin** [comment]
Can you confirm this problem exists on official version v0.3.1?

**Comment by fix** [comment]
yes, we have fixed it for 0.4.0
