### ISSUE TITLE
Error in Windows 10 install process

### ISSUE THREAD

**Issue by cezarsn** [fix/Lisk-Lite-Client#13]
$ npm install

> electron-prebuilt@1.2.8 postinstall C:_my\data\Lisk-Lite-Client-master\node_m                                                                                                                                                 odules\electron-prebuilt
> node install.js

Downloading electron-v1.2.8-win32-x64.zip
[============================================>] 100.0% of 52.59 MB (1.62 MB/s)

> LiskClient@1.0.0-beta3 postinstall C:_my\data\Lisk-Lite-Client-master
> install-app-deps

'install-app-deps' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\                                                                                                                                                 node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! LiskClient@1.0.0-beta3 postinstall: `install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the LiskClient@1.0.0-beta3 postinstall script 'install-app-de                                                                                                                                                 ps'.
npm ERR! This is most likely a problem with the LiskClient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs LiskClient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls LiskClient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:_my\data\Lisk-Lite-Client-master\npm-debug.log

**Comment by cezarsn** [comment]
maybe is this https://github.com/electron-userland/electron-builder/issues/376

**Comment by cezarsn** [comment]
http://stackoverflow.com/questions/17035399/why-this-error-happend-nodejs-error-write-eio
I will try this but maybe we can do this in the install process

Is not solving the issue

**Comment by fix** [comment]
Well remember i had the same issue somehow in mac. I think i fixed it by:
- upgrading node
- then removing node_modules/ and doing again `npm install`
