### ISSUE TITLE
Try to remove Win10 smartscreen warning

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [fix/Lisk-Lite-Client#19]
Verify to remove Win10 smartscreen warning on the execution of the installer. (LiskClient.Setup.1.0.0.exe)

Maybe check about the publisher field of the installer.
It say "do not execute" for a couple of seconds and after allow "execute anyway"

https://files.slack.com/files-pri/T1F2BJA1H-F1UGX1FL7/pasted_image_at_2016_07_23_06_10_pm.png

**Comment by Gr33nDrag0n69** [comment]
After some research, it seam smartscreen is a microsoft database.

The only way to get rid of it is creating a publisher name with a personnal signature and sign the install file. Each time someone install the setup file from his computer, the smart screen DB is checked and with time the publisher gain some trust for the file he sign.

Also found this:

The reputation score for your signing certificate increases over time and eventually the SmartScreen warning goes away

**Comment by Gr33nDrag0n69** [comment]
From my reading smartscreen is also present in win8/8.1

**Comment by fix** [comment]
ok digged a bit, i need to buy a certificate to sign the app ($500 for 1 year). Other wise i need to self sign, but the window won't disappear.
