### ISSUE TITLE
Unclean Win10 Uninstall

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [fix/Lisk-Lite-Client#27]
After client uninstall, some files are left on the target computer.

![uncleanuninstall](https://cloud.githubusercontent.com/assets/18356726/17265878/a2490138-55c0-11e6-9509-f45b6d0e87fb.png)

**Comment by fix** [comment]
I think it will be solved when the install script is working properly

**Comment by fix** [comment]
will provide a zip file instead of install script.
