### ISSUE TITLE
Suggested Changes to the "valuation" popup

### ISSUE THREAD

**Issue by Stoner19** [fix/Lisk-Lite-Client#3]
A few suggested changes/updates/enhancements to the valuation popup (this):

![screen shot 2016-06-03 at 4 21 39 pm](https://cloud.githubusercontent.com/assets/8030643/15794355/612fc6ae-29a7-11e6-921a-f42ee7921aba.png)
- Allow user to change the price/base currency. Instead of pinning it to USD some users may wish to see the value in BTC if they're actively trading it, or others may wish to see the value of their LSK in their own countries currency.
- Add commas to the `Capitalisation`

Otherwise it's a really really nice app. Props to you fix. Great work sir.

**Comment by fix** [comment]
working on it.
