### ISSUE TITLE
Add delegate not working with Lisk version 0.3.2

### ISSUE THREAD

**Issue by TheGoldenEye** [fix/Lisk-Lite-Client#34]
Seems there is a problem with version detection. 
Tested with https://login.lisk.io (v0.3.2)

![image](https://cloud.githubusercontent.com/assets/17945384/17592355/4bd54bbe-5fe2-11e6-8d31-ca89c7671144.png)

**Comment by fix** [comment]
well it is unimplemented because was waiting to work on it. Fixed on master
