### ISSUE TITLE
Send works but the transaction is not visible and does not pass

### ISSUE THREAD

**Issue by Buch86** [fix/Lisk-Lite-Client#46]
Can't send LISK. Send works number of the transaction shows. But transactions and explorer.lisk.io transactions are not. When you log on to https://login.lisk.io/. Get: Passphrase must be a valid BIP39 mnemonic code. Take LiskClientWindows-1.1.0. from 5 September. After the beginning of Forging can't send LISK. 8150 in my purse LISK. Ready to donate 10% of your balance for a solution to the problem.

**Comment by fix** [comment]
Ok saw the reason lisk client is not compatible with 0.5.0. Working on a fix

**Comment by fix** [comment]
hot fixed, releasing a new version now

**Comment by Buch86** [comment]
Where to download the new version of Lisk client. In https://github.com/fix/Lisk-Lite-Client/releases there is only old version. Or it will appear there a bit later.

**Comment by Buch86** [comment]
Thank you for the work. Where do I send 815 LISK in support of the project Lisk-Lite-Client.

**Comment by fix** [comment]
if you want to support the project, you can send to Lsk to  7136766316744460715L
Alternatively you can also vote for delegates of sponsors (in the vote for delegate tab)

Thanks for your support!
